// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAnalysisAndOpenBrowser(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RunSimulation(arg1:number,arg2:number,arg3:number,arg4:number,arg5:string):Promise<void>;

export function SelectFile():Promise<string>;
