// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function SimularRotina(arg1:Array<number>,arg2:Array<number>,arg3:number):Promise<Array<number>>;
